--
-- Sample dataset containing a number of Hotels in various Cities across the world.  The reviews are entirely fictional :)
--

-- =================================================================================================
-- AUSTRALIA

-- Brisbane
insert into city(country, name, state, map) values ('Australia', 'Brisbane', 'Queensland', '-27.470933, 153.023502')
insert into hotel(city_id, name, address, zip) values (1, 'Conrad Treasury Place', 'William & George Streets', '4001')

-- Melbourne
insert into city(country, name, state, map) values ('Australia', 'Melbourne', 'Victoria', '-37.813187, 144.96298')
insert into hotel(city_id, name, address, zip) values (2, 'The Langham', '1 Southgate Ave, Southbank', '3006')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (2, 0, '2005-05-10', 2, 4, 'Pretty average', 'I stayed in 2005, the hotel was nice enough but nothing special.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (2, 1, '2006-01-12', 4, 2, 'Bright hotel with big rooms', 'This hotel has a fantastic lovely big windows.  The room we stayed in had lots of space.  Recommended.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (2, 2, '2006-05-25', 3, 1, 'Pretty good', 'I liked this hotel and would stay again.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (2, 3, '2009-01-20', 3, 2, 'Nice clean rooms', 'The rooms are maintained to a high standard and very clean, the bathroom was spotless!!')

-- Sydney
insert into city(country, name, state, map) values ('Australia', 'Sydney', 'New South Wales', '-33.868901, 151.207091')
insert into hotel(city_id, name, address, zip) values (3, 'Swissotel', '68 Market Street', '2000')


-- =================================================================================================
-- CANADA

-- Montreal
insert into city(country, name, state, map) values ('Canada', 'Montreal', 'Quebec', '45.508889, -73.554167')
insert into hotel(city_id, name, address, zip) values (4, 'Ritz Carlton', '1228 Sherbrooke St', 'H3G1H6')


-- =================================================================================================
-- ISRAEL

-- Tel Aviv
insert into city(country, name, state, map) values ('Israel', 'Tel Aviv', '', '32.066157, 34.777821')
insert into hotel(city_id, name, address, zip) values (5, 'Hilton Tel Aviv', 'Independence Park', '63405')


-- =================================================================================================
-- JAPAN

-- Tokyo
insert into city(country, name, state, map) values ('Japan', 'Tokyo', '', '35.689488, 139.691706')
insert into hotel(city_id, name, address, zip) values (6, 'InterContinental Tokyo Bay', 'Takeshiba Pier', '105')


-- =================================================================================================
-- SPAIN

-- Barcelona
insert into city(country, name, state, map) values ('Spain', 'Barcelona', 'Catalunya', '41.387917, 2.169919')
insert into hotel(city_id, name, address, zip) values (7, 'Hilton Diagonal Mar', 'Passeig del Taulat 262-264', '08019')

-- =================================================================================================
-- SWITZERLAND

-- Neuchatel
insert into city(country, name, state, map) values ('Switzerland', 'Neuchatel', '', '46.992979, 6.931933')
insert into hotel(city_id, name, address, zip) values (8, 'Hotel Beaulac', ' Esplanade Leopold-Robert 2', '2000')


-- =================================================================================================
-- UNITED KINGDOM

-- Bath
insert into city(country, name, state, map) values ('UK', 'Bath', 'Somerset', '51.381428, -2.357454')
insert into hotel(city_id, name, address, zip) values (9, 'The Bath Priory Hotel', 'Weston Road', 'BA1 2XT')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 0, '2000-01-23', 4, 1, 'A lovely hotel', 'We stayed here after a wedding and it was fantastic.  Recommend to all.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 1, '2000-08-04', 3, 1, 'Very special', 'A very special hotel with lovely staff.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 2, '2001-01-01', 2, 4, 'Nice but too hot', 'Stayed during the summer heat wave (exceptional for England!) and the room was very hot.  Still recommended.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 3, '2002-01-20', 3, 1, 'Big rooms and a great view', 'Considering how central this hotel is the rooms are a very good size.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 4, '2002-11-03', 2, 1, 'Good but pricey', 'A nice hotel but be prepared to pay over the odds for your stay.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 5, '2003-09-18', 4, 1, 'Fantastic place', 'Just lovely.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 6, '2004-03-21', 4, 3, 'A very special place', 'I stayed here in 2004 and found it to be very relaxing, a nice pool and good gym is cherry on the cake.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 7, '2004-04-10', 0, 0, 'Terrible', 'I complained after I was told I could not check out after 11pm.  Ridiculous!!!')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 8, '2004-12-20', 4, 4, 'A perfect location', 'Central location makes this a perfect hotel.  Be warned though, it''s not cheap.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 9, '2005-04-19', 3, 2, 'Expensive but worth it', 'Dig deep into your pockets and enjoy this lovely City and fantastic hotel.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 10, '2005-05-21', 4, 1, 'The best hotel in the area', 'Top hotel in the area, would not stay anywhere else.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 11, '2005-11-17', 4, 2, 'Lovely hotel, fantastic grounds', 'The garden upkeep run into thousands (perhaps explaining why the rooms are so much) but so lovely and relaxing.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 12, '2006-01-04', 3, 4, 'Gorgeous Top Quality Hotel', 'Top draw stuff.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 13, '2006-01-21', 4, 1, 'Fabulous Hotel and Restaurant', 'The food at this hotel is second to none, try the peppered steak!')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 14, '2006-01-29', 4, 4, 'Feels like home', 'A lovely home away from home.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 15, '2006-03-21', 1, 1, 'Far too expensive', 'Overpriced, Overpriced, Overpriced!!')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 16, '2006-05-10', 4, 1, 'Excellent Hotel, Wonderful Staff', 'The staff went out of their way to help us after we missed our last train home, organising a Taxi back to Newport even after we had checked out.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 17, '2007-09-11', 3, 2, 'The perfect retreat', 'If you want a relaxing stay, this is the place.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 18, '2008-06-01', 3, 3, 'Lovely stay, fantastic staff', 'As other reviews have noted, the staff in this hotel really are the best in Bath.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 19, '2009-05-14', 4, 2, 'Can''t Wait to go back', 'We will stay again for sure.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 20, '2010-04-26', 4, 1, 'Amazing Hotel', 'We won a trip here after entering a competition.  Not sure we would pay the full price but such a wonderful place.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (9, 21, '2010-10-26', 2, 2, 'Dissapointed', 'The pool was closed, the chief was ill, the staff were rude my wallet is bruised!')
insert into hotel(city_id, name, address, zip) values (9, 'Bath Travelodge', 'Rossiter Road, Widcombe Basin', 'BA2 4JP')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 0, '2002-08-21', 0, 2, 'Terrible hotel', 'One of the worst hotels that I have ever stayed in.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 1, '2003-01-28', 0, 0, 'Rude and unpleasant staff', 'The staff refused to help me with any aspect of my stay, I will not stay here again.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 2, '2004-06-17', 1, 0, 'Below par', 'Don''t stay here!!')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 3, '2005-07-12', 0, 1, 'Small and Unpleasant', 'The room was far too small and felt unclean.  Not recommended.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 4, '2006-01-07', 1, 4, 'Cheap if you are not fussy', 'This hotel has some rough edges but I challenge you to find somewhere cheaper.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 5, '2006-01-13', 0, 2, 'Terrible', 'Just terrible!')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 6, '2006-03-25', 0, 0, 'Smelly and dirty room', 'My room smelt of damp and I found the socks of the previous occupant under my bed.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 7, '2006-04-09', 0, 4, 'Grim', 'Grim.  I would try elsewhere before staying here.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 8, '2006-08-01', 1, 3, 'Very Noisy', 'Building work during the day and a disco at night.  Good grief!')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 9, '2009-01-03', 1, 4, 'Tired and falling down', 'This hotel is in serious need of refurbishment, the windows are rotting, the paintwork is tired and the carpets are from the 1970s.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 10, '2009-07-20', 0, 0, 'Not suitable for human habitation', 'I would not put my dog up in this hotel.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 11, '2010-05-20', 1, 0, 'Conveient for the railway', 'Average place but useful if you need to commute')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 12, '2010-01-22', 2, 2, 'Not as bad as the reviews', 'Some of the reviews seem a bit harsh, it''s not too bad for the price.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (10, 13, '2011-01-10', 3, 1, 'Reburished and nice', 'Looks like this hotel has had a major facelift.  If you have stayed before 2011 perhaps it''s time to give this hotel another try.  Very good value for money and pretty nice.')

-- London
insert into city(country, name, state, map) values ('UK', 'London', '', '51.500152, -0.126236')
insert into hotel(city_id, name, address, zip) values (10, 'Melia White House', 'Albany Street', 'NW1 3UP')

-- Southampton
insert into city(country, name, state, map) values ('UK', 'Southampton', 'Hampshire', '50.902571, -1.397238')
insert into hotel(city_id, name, address, zip) values (11, 'Chilworth Manor', 'The Cottage, Southampton Business Park', 'SO16 7JF')


-- =================================================================================================
-- USA

-- Atlanta
insert into city(country, name, state, map) values ('USA', 'Atlanta', 'GA', '33.748995, -84.387982')
insert into hotel(city_id, name, address, zip) values (12, 'Marriott Courtyard', 'Tower Place, Buckhead', '30305')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (13, 0, '2009-01-20', 3, 0, 'Better than most', 'Most other hotels is this area are a bit ropey, this one is actually pretty good.')
insert into hotel(city_id, name, address, zip) values (12, 'Ritz Carlton', 'Peachtree Rd, Buckhead', '30326')
insert into hotel(city_id, name, address, zip) values (12, 'Doubletree', 'Tower Place, Buckhead', '30305')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (15, 0, '2006-01-12', 2, 3, 'No fuss hotel', 'Cheap, no fuss hotel.  Good if you are travelling on business and just need a place to stay.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (15, 1, '2009-01-20', 2, 2, 'Nice area but small rooms', 'The area felt nice and safe but the rooms are a little on the small side')

-- Chicago
insert into city(country, name, state, map) values ('USA', 'Chicago', 'IL', '41.878114, -87.629798')
insert into hotel(city_id, name, address, zip) values (13, 'Hotel Allegro', '171 West Randolph Street', '60601')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (16, 0, '2009-12-15', 3, 2, 'Cheap and Recommended', 'Good value for money, can''t really fault it.')

-- Eau Claire
insert into city(country, name, state, map) values ('USA', 'Eau Claire', 'WI', '44.811349, -91.498494')
insert into hotel(city_id, name, address, zip) values (14, 'Sea Horse Inn', '2106 N Clairemont Ave', '54703')
insert into hotel(city_id, name, address, zip) values (14, 'Super 8 Eau Claire Campus Area', '1151 W Macarthur Ave', '54701')

-- Hollywood
insert into city(country, name, state, map) values ('USA', 'Hollywood', 'FL', '26.011201, -80.14949')
insert into hotel(city_id, name, address, zip) values (15, 'Westin Diplomat', '3555 S. Ocean Drive', '33019')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (19, 0, '2006-01-11', 0, 0, 'Avoid', 'The hotel has a very bad reputation.  I would avoid it if I were you.')

-- Miami
insert into city(country, name, state, map) values ('USA', 'Miami', 'FL', '25.788969, -80.226439')
insert into hotel(city_id, name, address, zip) values (16, 'Conrad Miami', '1395 Brickell Ave', '33131')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (20, 0, '2010-01-09', 3, 2, 'Close to the local attractions', 'Fantastic access to all the local attractions mean you won''t mind the small rooms.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (20, 1, '2010-09-10', 2, 2, 'Good value and friendly', 'Not expensive and very welcoming staff. I would stay again.')

-- Melbourne
insert into city(country, name, state, map) values ('USA', 'Melbourne', 'FL', '28.083627, -80.608109')
insert into hotel(city_id, name, address, zip) values (17, 'Radisson Suite Hotel Oceanfront', '3101 North Hwy', '32903')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (21, 0, '2005-06-15', 3, 3, 'A very nice hotel', 'I can''t fault this hotel and I have stayed here many times.  Always friendly staff and lovely atmosphere.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (21, 1, '2006-01-20', 2, 4, 'Comfortable and good value', 'To complaints at all.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (21, 2, '2007-08-21', 3, 1, 'Above average', 'Better than a lot of hotels in the area and not too pricey.')

-- New York
insert into city(country, name, state, map) values ('USA', 'New York', 'NY', '40.714353, -74.005973')
insert into hotel(city_id, name, address, zip) values (18, 'W Union Hotel', 'Union Square, Manhattan', '10011')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (22, 0, '2002-01-19', 0, 1, 'Too noisy, too small', 'The city never sleeps and neither will you if you say here.  The rooms are small and the sound insulation is poor!')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (22, 1, '2004-03-10', 1, 4, 'Overpriced', 'Far too much money for such a tiny room!')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (22, 2, '2007-04-11', 2, 0, 'So so, nothing special', 'Not brilliant but not too bad either.')
insert into hotel(city_id, name, address, zip) values (18, 'W Lexington Hotel', 'Lexington Ave, Manhattan', '10011')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (23, 0, '2004-07-21', 3, 2, 'Excellent location', 'So close to the heart of the city.  Recommended.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (23, 1, '2006-05-20', 3, 1, 'Very nice', 'I can''t fault this hotel, clean, good location and nice staff.')
insert into hotel(city_id, name, address, zip) values (18, '70 Park Avenue Hotel', '70 Park Avenue', '10011')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (24, 0, '2003-11-10', 4, 1, 'Great!!', 'I own this hotel and I think it is pretty darn good.')

-- Palm Bay
insert into city(country, name, state, map) values ('USA', 'Palm Bay', 'FL', '28.034462, -80.588665')
insert into hotel(city_id, name, address, zip) values (19, 'Jameson Inn', '890 Palm Bay Rd NE', '32905')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (25, 0, '2005-10-20', 3, 2, 'Fantastical', 'This is the BEST hotel in Palm Bay, not complaints at all.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (25, 1, '2006-01-12', 4, 1, 'Top marks', 'I rate this hotel 5 stars, the best in the area by miles.')

-- San Francisco
insert into city(country, name, state, map) values ('USA', 'San Francisco', 'CA', '37.77493, -122.419415')
insert into hotel(city_id, name, address, zip) values (20, 'Marriot Downtown', '55 Fourth Street', '94103')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (26, 0, '2006-07-02', 2, 3, 'Could be better', 'I stayed in late 2006 with work, the room was very small and the restaurant does not stay open very late.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (26, 1, '2008-07-01', 1, 4, 'Brrrr cold!', 'My room was freezing cold, I would not recommend this place.')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (26, 2, '2009-01-05', 3, 2, 'Nice for money', 'You can''t really go wrong here for the money.  There may be better places to stay but not for this price.')

-- Washington
insert into city(country, name, state, map) values ('USA', 'Washington', 'DC', '38.895112, -77.036366')
insert into hotel(city_id, name, address, zip) values (21, 'Hotel Rouge', '1315 16th Street NW', '20036')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (27, 0, '2000-01-29', 0, 2, 'Never again', 'I will never ever stay here again!!  They wanted extra cash to get fresh batteries for the TV remote')
insert into review(hotel_id, idx, check_in_date, rating, trip_type, title, details) values (27, 1, '2006-02-20', 0, 0, 'Avoid', 'This place is the pits, they charged us twice for a single night stay.  I only got refunded after contacting my credit card company.')


-- ARGO INSERT
-- INTO CSC
INSERT INTO csc (nick, descr, params) VALUES ('ICMP','Test di connettività tramite ICMP (echo request / echo reply)','dest:ipstring');
INSERT INTO csc (nick, descr, params) VALUES ('HTTP_Head','Test di accessibilità tramite HTTP/HEAD ','uri:urlstring;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('TCP_Connect','Test di connessione a servizio TCP','dest:ipstring;port:number');
INSERT INTO csc (nick, descr, params) VALUES ('SqlServerDB','Servizio di verifica db Microsoft SqlServer con select','user:string;password:string;dburi:string;dbname:string;select:string');
INSERT INTO csc (nick, descr, params) VALUES ('MySqlDB','Servizio di verifica db MySql con select','user:string;password:string;dburi:string;dbname:string;select:string');
INSERT INTO csc (nick, descr, params) VALUES ('SNMP_Check','Test di presenza agent SNMP','dest:ipstring;community:string');
INSERT INTO csc (nick, descr, params) VALUES ('SNMP_Range','Test sui valori di variabili MIB via SNMP','dest:ipstring;community:string;oidvar:string;condition:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTML_SearchText','Ricerca di stringa su documento HTML ottenuto via HTTP','uri:urlstring;search:string;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTTP_Proxied','Test di accessibilità tramite HTTP/HEAD attraverso un proxy','uri:urlstring;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('DNS_Query','Query su DNS Server','server:ipstring;query_type:string;query:string');
INSERT INTO csc (nick, descr, params) VALUES ('POP3_Box_Check','Test di accesso a mailbox via POP3','server:ipstring;port:int;username:string;passwd:string');
INSERT INTO csc (nick, descr, params) VALUES ('SMTP_Send_Check','Test di sessione su server SMTP','server:ipstring;port:int;sender_host:string;sender:string;recipient:string');
INSERT INTO csc (nick, descr, params) VALUES ('XML_Check','Test sul valore di un tag in un documento XML','uri:string;xmltag:string;xmlval:string');
INSERT INTO csc (nick, descr, params) VALUES ('Post_CSC_AUTH','Test di sessione su server SMTP','serverSMTP:ipstring;portSMTP:int;serverPOP3:ipstring;portPOP3:int;usernamePOP3:string;passwdPOP3:string;sender_host:string;usernameSMTP:string;passwdSMTP:string;deliveryTime:int;sender:string;recipient:string;');
INSERT INTO csc (nick, descr, params) VALUES ('Post_CSC','Servizio di verifica Posta con SMTP senza autenticazione','serverSMTP:ipstring;portSMTP:int;serverPOP3:ipstring;portPOP3:int;usernamePOP3:string;passwdPOP3:string;sender_host:string;deliveryTime:int;sender:string;recipient:string;');
INSERT INTO csc (nick, descr, params) VALUES ('SOAP_Invoke','Invocazione di metodo SOAP','listener:string;method:string;expected:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTTP_C_SearchText','Ricerca di stringa su documento HTML ottenuto via HTTP con cookie ','uri:urlstring;search:string;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('OracleDB',' Servizio di verifica db con select',' user:string;password:string;dburi:string;select:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTTPS_Head','Test di accessibilità tramite HTTPS/HEAD ','uri:urlstring;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTTPS_SearchText','Ricerca di stringa su documento HTML ottenuto via HTTPS','uri:urlstring;search:string;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTTPS_Proxied','Test di accessibilità tramite HTTPS/HEAD attraverso un proxy','uri:urlstring;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTTPS_C_SearchText','Ricerca di stringa su documento HTML ottenuto via HTTPS con cookie','uri:urlstring;search:string;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTTPS_Head_N_Cert','Test di accessibilità tramite HTTPS/HEAD senza importare il certificato nella jvm','uri:urlstring;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTTPS_SearchText_N_C','Ricerca di stringa su documento HTML ottenuto via HTTPS senza importare il certificato nella jvm','uri:urlstring;search:string;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTTP_Login_Form',' Servizio di verifica su applicazioni DOT NET con autenticazione NT','uri:urlstring;search:string;auth_username:string;auth_passwd:string;connection_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('POP_SMTP_Validate','Test di invio ricezione','serverSMTP:ipstring;portSMTP:int;serverPOP3:ipstring;portPOP3:int;usernamePOP3:string;passwdPOP3:string;sender_host:string;usernameSMTP:string;passwdSMTP:string;deliveryTime:int;sender:string;recipient:string;id_check:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTTP_SSO_RedirectURL','Redirect verso sso con post token','uri:urlstring;search:string;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('HTTPS_SSO_RedirURL','Redirect verso sso con post token','uri:urlstring;search:string;auth_username:string;auth_passwd:string;proxy_host:string;proxy_port:string;proxy_user:string;proxy_passwd:string;request_method:string;request_parameters:string;connection_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('Telnet_test','Test attività porta con protocollo telnet','machineName:string;port:string');
INSERT INTO csc (nick, descr, params) VALUES ('SNMP_Walking','Test servizio via snmp','dest:ipstring;community:string;oidvar:string;condition:string');
INSERT INTO csc (nick, descr, params) VALUES ('SNMP_CPU_TEMP','Test temperatura cpu via snmp','dest:ipstring;community:string;version:string;mib:string;oidvarTemp:string;oidvarThreshold:string;deltaMaxTemperature:string');
INSERT INTO csc (nick, descr, params) VALUES ('ProcessAlive','Test processo stand-alone','daemon:string;arg_no:number;arg_value:string');
INSERT INTO csc (nick, descr, params) VALUES ('ClientFormLogin','Test di navigazione applicazione web','host:string;port:string;protocol:string;uri:urlstring;search:string;proxy_host:string;proxy_port:string;proxy_protocolt:string;auth_username:string;auth_passwd:string;login_page:string;get_page:string;request_parameters:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('ClientFormSearch','Test di ricerca dati con navigazione applicazione web','host:string;port:string;protocol:string;uri:urlstring;search:string;proxy_host:string;proxy_port:string;proxy_protocolt:string;auth_username:string;auth_passwd:string;login_page:string;get_page:string;request_parameters:string;search_parameters:string;search_page:string;connection_timeout:string;data_receiving_timeout:string');
INSERT INTO csc (nick, descr, params) VALUES ('Ntp_Sync','','remote_address:string;tolerance_limit:number');
INSERT INTO csc (nick, descr, params) VALUES ('Sender_PEC','Test invio mail da PEC','serverSMTP:string;portSMTP:int;sender_host:ipstring;sender:string;recipient:string;usernameSMTP:string;passwdSMTP:string;subject: string ');
INSERT INTO csc (nick, descr, params) VALUES ('ClientSoapWS','Test di connettività verso Web Services MDI','endpoint:string;user:string;password:string;digest:string');

--INTO OBJECTS
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (1,'argo','Descrizione caratteristiche oggetto','container','container',0,0,30,33,NULL,NULL,'package_ciano.gif','dest=127.0.0.1',NULL,'http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (10,'TestArgo','','container','container',0,1,60,100,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (13,'JBoss_MetaAgent','JBoss_MetaAgent','controller','service',3,10,360,100,NULL,NULL,NULL,'dest=127.0.0.1;port=8080;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (14,'Tomcat_DispatcherUnix','','controller','service',3,10,3600,-2,NULL,NULL,NULL,'dest=192.168.100.85;port=8180;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (15,'ArgoLogin','<a href=''https://mail.google.com/'' target=''_blank''><font color=''white''>Procedura Operativa 1</font></a>','controller','application',2,10,600,100,NULL,NULL,NULL,'uri=http://127.0.0.1:8080/argo/login.jsp/;auth_username=argo;auth_passwd=argo;proxy_host=;proxy_port=;proxy_user=;proxy_passwd=;request_method=;request_parameters=;connection_timeout=;data_receiving_timeout=20000;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (22,'Applicazioni','','container','container',0,1,60,0,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (23,'OSTIAMARE','','container','container',0,22,60,0,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (24,'Ostiamare-HomePage','http://www.ostiamare.it/','controller','application',8,23,3600,0,NULL,NULL,NULL,'uri=http://www.ostiamare.com/;search=Ostiamare;auth_username=;auth_passwd=;proxy_host=;proxy_port=;proxy_user=;proxy_passwd=;request_method=;request_parameters=;connection_timeout=120;data_receiving_timeout=;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (31,'POSTA-STM','','container','container',0,22,60,0,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (36,'STM','','container','container',0,22,60,0,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (37,'WebMail-StmItalia-com','https://mail.stmitalia.com/zimbra/','controller','application',24,31,3600,0,NULL,NULL,NULL,'uri=https://mail.stmitalia.com?username=argo.argo;search=argo.argo;auth_username=argo.argo;auth_passwd=argo.alda;proxy_host=;proxy_port=;proxy_user=;proxy_passwd=;request_method=;request_parameters=;connection_timeout=;data_receiving_timeout=;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (38,'Stm-Italia-HomePage','http://www.stmitalia.com','controller','application',8,36,3600,0,NULL,NULL,NULL,'uri=http://www.stmitalia.it/;search=Stm Group;auth_username=;auth_passwd=;proxy_host=;proxy_port=;proxy_user=;proxy_passwd=;request_method=;request_parameters=;connection_timeout=;data_receiving_timeout=;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (39,'Mail-StmItalia-InvioeRicezione','Simulazione su POP3 SMTP','controller','service',26,31,3600,0,NULL,NULL,NULL,'serverSMTP=mail.stmitalia.com;portSMTP=25;serverPOP3=mail.stmitalia.com;portPOP3=110;usernamePOP3=argo.argo;passwdPOP3=argo.alda;sender_host=127.0.0.1;usernameSMTP=argo.argo;passwdSMTP=argo.alda;deliveryTime=100;sender=argo.argo@stmitalia.com;recipient=argo.argo@stmitalia.com;id_check=13;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (42,'StmItalia-Pop3-Telnet','Telnet mail.stmitalia.com 110','controller','device',3,31,3600,0,NULL,NULL,NULL,'dest=mail.stmitalia.com;port=110;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (43,'StmItalia-Smtp-Telnet','Telnet mail.stmitalia.com 25','controller','device',3,31,3600,0,NULL,NULL,NULL,'dest=mail.stmitalia.com;port=25;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (50,'AST','Manutenzione AST','container','container',0,22,60,0,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (65,'STM_to_STM','controller invio e ricezione posta interna','controller','service',26,64,3600,0,NULL,NULL,NULL,'serverSMTP=mail.stmitalia.com;portSMTP=25;serverPOP3=mail.stmitalia.com;portPOP3=110;usernamePOP3=testargo;passwdPOP3=argo.alda;sender_host=127.0.0.1;usernameSMTP=testargo;passwdSMTP=argo.alda;deliveryTime=600;sender=testargo@stmitalia.com;recipient=testargo@stmitalia.com;id_check=101;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (76,'From_STM','controller invio e ricezione posta interna','controller','service',26,71,3600,0,NULL,NULL,NULL,'serverSMTP=mail.stmitalia.com;portSMTP=25;serverPOP3=mail.stmitalia.com;portPOP3=110;usernamePOP3=testargo;passwdPOP3=argo.alda;sender_host=127.0.0.1;usernameSMTP=testargo;passwdSMTP=argo.alda;deliveryTime=300;sender=testargo@stmitalia.com;recipient=testargo@stmitalia.com;id_check=103;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (77,'Internet_Az','','container','container',0,1,60,0,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (80,'ICMPInternet attraverso FASTWEB','Gateway 3','controller','application',1,77,3600,0,NULL,NULL,NULL,'dest=www.google.it;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (82,'ICMPInternet attraverso ITNET','Gateway 1','controller','application',1,77,600,-2,NULL,NULL,NULL,'dest=217.12.3.11;','','http://192.168.100.155:80/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (84,'Router_FastwebDaNodo1','','controller','device',1,77,60,-2,NULL,NULL,NULL,'dest=192.168.100.3;','','http://192.168.100.155:80/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (85,'Router_ItnetDaNodo1','','controller','device',1,77,60,-2,NULL,NULL,NULL,'dest=192.168.100.1;','','http://192.168.100.155:80/soap/servlet/rpcrouter',1,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (89,'HTTPInternet attraverso FASTWEB','Gateway 3','controller','application',8,77,3600,-2,NULL,NULL,NULL,'uri=http://www.gogle.it;search=Ricerca avanzata;auth_username=;auth_passwd=;proxy_host=;proxy_port=;proxy_user=;proxy_passwd=;request_method=;request_parameters=;connection_timeout=;data_receiving_timeout=;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (90,'Data Protector','Monitoraggio Back-up','container','container',0,1,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (91,'Backup client service','HP OpenView Storage Data Protector','controller','service',30,90,3600,-2,NULL,NULL,NULL,'dest=192.168.100.75;community=stmbeng;oidvar=.1.3.6.1.2.1.25.4.2.1.2.1;condition=OmniInet.exe;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (92,'Cell Manager database service','HP OpenView Storage Data Protector','controller','service',30,90,3600,-2,NULL,NULL,NULL,'dest=192.168.100.75;community=stmbeng;oidvar=.1.3.6.1.2.1.25.4.2.1.2.1;condition=rds.exe;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (93,'Cell Manager service','HP OpenView Storage Data Protector','controller','service',30,90,3600,-2,NULL,NULL,NULL,'dest=192.168.100.75;community=stmbeng;oidvar=.1.3.6.1.2.1.25.4.2.1.2.1;condition=crs.exe;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (94,'ICMP DataProtector','','controller','service',1,90,3600,-2,NULL,NULL,NULL,'dest=192.168.100.75;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (95,'ICMP STMRMS06','Backup disco usb 500 Gb','controller','service',1,90,3600,-2,NULL,NULL,NULL,'dest=192.168.100.30;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (96,'AntiSpam','','container','container',0,1,3600,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (98,'ICMP Server Antispam','','controller','service',1,96,3600,-2,NULL,NULL,NULL,'dest=192.168.100.74;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (99,'Temperatura Cpu Ced','Controlla che la temperatura dei server della sala ced sia all''interno dei range ammissibili','container','container',0,1,600,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (100,'Temperatura CPU STMRMS06','funziona = temperatura nei limiti - non funziona = riscaldamento urgente','controller','service',31,99,600,-2,NULL,NULL,NULL,'dest=192.168.100.30;community=stmbeng;version=1;mib=HOST-RESOURCES-MIB;oidvarTemp=.1.3.6.1.4.1.232.6.2.6.8.1.4.0;oidvarThreshold=.1.3.6.1.4.1.232.6.2.6.8.1.5.0;deltaMaxTemperature=10;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (101,'Temperatura CPU STMRMW1','funziona = temperatura nei limiti - non funziona = riscaldamento urgente','controller','service',31,99,600,-2,NULL,NULL,NULL,'dest=192.168.100.80;community=public;version=1;mib=HOST-RESOURCES-MIB;oidvarTemp=.1.3.6.1.4.1.232.6.2.6.8.1.4.0;oidvarThreshold=.1.3.6.1.4.1.232.6.2.6.8.1.5.0;deltaMaxTemperature=50;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (102,'Temperatura CPU STMRMS05','funziona = temperatura nei limiti - non funziona = riscaldamento urgente','controller','service',31,99,600,-2,NULL,NULL,NULL,'dest=192.168.100.22;community=stmbeng;version=1;mib=HOST-RESOURCES-MIB;oidvarTemp=.1.3.6.1.4.1.232.6.2.6.8.1.4.0;oidvarThreshold=.1.3.6.1.4.1.232.6.2.6.8.1.5.0;deltaMaxTemperature=10;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (103,'La Spezia','Monitoraggio STM Sede La Spezia','container','container',0,1,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (104,'ICMP La Spezia','PING 192.168.10.1  Gateway 3','controller','service',1,103,600,-2,NULL,NULL,NULL,'dest=192.168.10.1;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (105,'Temperatura Ambientale','Temperatura ambientale sala CED','container','container',0,1,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (107,'TEMPerr service','Servizio di monitoraggio temperatura ambientale con USB','controller','service',30,105,3600,-2,NULL,NULL,NULL,'dest=192.168.100.116;community=stmbeng;oidvar=.1.3.6.1.2.1.25.4.2.1.2.1;condition=Utac.exe;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (108,'Stampanti','Stampanti','container','container',0,1,600,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (109,'Stampante HP Laserjet 3550 Color','Ubicazione: Stanza Marco Munafò','controller','service',1,108,600,-2,NULL,NULL,NULL,'dest=192.168.101.11;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (110,'Stampante HP Laserjet 2200DN','Ubicazione: Stanza Marco Munafò','controller','service',1,108,600,-2,NULL,NULL,NULL,'dest=192.168.101.12;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (111,'Stampante HPOfficeJet Pro K550','Ubicazione: Stanza Valentina/Antonella','controller','service',1,108,6000,-2,NULL,NULL,NULL,'dest=192.168.101.13;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (112,'Stampante HPd315','Ubicazione: Stanza Valentina/Antonella','controller','service',1,108,6000,-2,NULL,NULL,NULL,'dest=192.168.101.14;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (113,'Stampante HP2420n','Ubicazione: Stanza Nicoletta/Fabrizio','controller','service',1,108,600,-2,NULL,NULL,NULL,'dest=192.168.101.15;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (116,'AST','Controllo sito ast','controller','service',2,50,3600,0,NULL,NULL,NULL,'uri=http://www.aziendasicilianatrasporti.it/auth_username=;auth_passwd=;proxy_host=;proxy_port=;proxy_user=;proxy_passwd=;request_method=;request_parameters=;connection_timeout=;data_receiving_timeout=;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (118,'BUSINESS ENGINEERING','Sito web Business Engineering','container','container',0,22,3600,0,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (119,'Sito Business Engineering','Business Engineering S.r.l.','controller','application',2,118,3600,0,NULL,NULL,NULL,'uri=http://172.16.110.12/opencms/bueng/HOME/index.html;auth_username=;auth_passwd=;proxy_host=;proxy_port=;proxy_user=;proxy_passwd=;request_method=;request_parameters=;connection_timeout=;data_receiving_timeout=;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (125,'Monitoraggio IAG','Portale IAG','container','container',0,1,600,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (126,'IAG Https Autenticazione','Autenticazione IAG','controller','service',24,125,1200,-2,NULL,NULL,NULL,'uri=https://mdi-iag.sita.aero/iag/j_security_check?j_username=SARGOIAG&j_password=Birillo1&jsessionid=0;search=exceeded;auth_username=;auth_passwd=;proxy_host=;proxy_port=;proxy_user=;proxy_passwd=;request_method=post;request_parameters=;connection_timeout=50000;data_receiving_timeout=50000;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (127,'IAG Portale','Portale IAG','controller','service',23,125,1200,-2,NULL,NULL,NULL,'uri=https://mdi-iag.sita.aero/iag/;auth_username=;auth_passwd=;proxy_host=;proxy_port=;proxy_user=;proxy_passwd=;request_method=;request_parameters=;connection_timeout=60000;data_receiving_timeout=60000;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (128,'SenderPEC','','controller','service',39,10,3600,-2,NULL,NULL,NULL,'serverSMTP=smtp.telecompost.it;portSMTP=465;sender_host=127.0.0.1;sender=argostg@bcs.telecompost.it;recipient=alda.biunda@stmitalia.com;usernameSMTP=argostg@bcs.telecompost.it;passwdSMTP=argostg.2011;subject=ciao;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (132,'Tomcat_Dispatcher82','','controller','service',3,10,360,-2,NULL,NULL,NULL,'dest=192.168.100.82;port=8080;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (133,'BCS','Navigazione BCS','container','container',0,1,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (134,'LoginBCS','','controller','service',33,133,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=SITA - INTERNAL;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/home;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (136,'Acquisizione Dati','Acquisizione Dati','container','container',0,133,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (137,'Regole Vettori','<a href=3D''https://fe01/cpr/CarrierRules.form''>vai alla procedura </a>','controller','service',33,136,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=flightsNoRule;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/cpr/CarrierRules.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (140,'Crea Scansione Pre-Partenza','Crea Scansione Pre-Partenza','controller','service',33,136,60,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=FIELD_DEFINITIONS_PFS_SCHEDULE_TYPE;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/idetectdb/createPreDepartureScan.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (141,'Cerca Scansione Pre-Partenza','Cerca Scansione Pre-Partenza','controller','service',33,136,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=FIELD_DEFINITIONS_PFS_SCAN_STATUS;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/idetectdb/searchPreDepartureScan.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (142,'Gestione del Rischio','Gestione del Rischio','container','container',0,133,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (143,'Valutazione del Rischio','Valutazione del Rischio','controller','service',33,142,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=FIELD_DEFINITIONS_FLIGHT_ROUTE;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/iRiskAssessment.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (144,'Controllo Passaporti','Controllo Passaporti','controller','service',33,142,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=reOrderSubAlertList;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/iRiskPassportControl.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (145,'Alert Attivi','Alert Attivi','controller','service',33,142,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=div_activeAlerts;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/iRiskActiveAlerts.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (146,'Ricerca','Ricerca','container','container',0,133,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (147,'Ricerca Volo','Ricerca Volo','controller','service',33,146,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=flightSearchPrint.pdf;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/idetectdb/flightSearch.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (148,'Ricerca Viaggiatore','Ricerca Viaggiatore','controller','service',33,146,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=FIELD_DEFINITIONS_GENDER_GEN;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/idetectdb/travellerSearch.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (149,'Ricerca Avanzata','Ricerca Viaggiatore','controller','service',33,146,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=FIELD_DEFINITIONS_DOCUMENT_NUMBER_DOC_NO;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/idetectdb/advancedSearch.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (150,'Ricerca Alert Viaggiatori','Ricerca Alert Viaggiatori','controller','service',33,146,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=FIELD_DEFINITIONS_TYPE_OF_CRIME;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/iRiskTravellerAlertSearch.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (151,'Ricerca Alert Complessi','Ricerca Alert Complessi','controller','service',33,146,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=iRiskClusterAlertSearchPrint.pdf;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/iRiskClusterAlertView.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (152,'Ricerca Alert ad Alta Priorita','Ricerca Alert ad Alta Priorita','controller','service',33,146,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=iRiskHighPriorityAlertSearchPrint.pdf;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/iRiskHighPriorityAlertSearch.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (153,'Ricerca Eventi Audit','Ricerca Eventi Audit','controller','service',33,146,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=auditSearchPrint.pdf;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/audit//auditSearch.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (155,'Lista Sospetti','Lista Sospetti','container','container',0,133,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (156,'Ricerca Sospetto','Ricerca Sospetto','controller','service',33,155,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=deleteTravellerPopin;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/wi/viewTargets.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (157,'Aggiungi Sospetto','Aggiungi Sospetto','controller','service',33,155,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=FIELD_DEFINITIONS_NUM_PROTOCOLLO;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/wi/addTarget.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (158,'Configurazione','Configurazione','container','container',0,133,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (159,'Matrice Dinamica Crimini','Matrice Dinamica Crimini','controller','service',33,158,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=FIELD_DEFINITIONS_CURRENT_THRESHOLD;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/iRiskCrimeRules.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (160,'Statistiche','Statistiche','container','container',0,133,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (161,'Statistica Volume Dati Viaggiatori','Statistica Volume Dati Viaggiatori','controller','service',33,160,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=FIELD_DEFINITIONS_CARRIER_CODE;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/idetectdb/statisticsTravellerDataVolume.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (162,'Report Alert','Report Alert','controller','service',33,160,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=div_statsAlertGeneration;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/iRiskGenerateReports.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (163,'Statistica Qualita Dati Viaggiatori','Statistica Qualita Dati Viaggiatori','controller','service',33,160,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=STATISTICS_TRAVELLER_DATA_QUALITY;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/idetectdb/statisticsTravellerDataQuality.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (164,'Statistica Gestione Alert','Statistica Gestione Alert','controller','service',33,160,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=div_statsAlertHandling;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/iRiskAlertHandlingStats.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (165,'Statistica Generazione Alert','Statistica Generazione Alert','controller','service',33,160,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=div_statsAlertGeneration;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/iRiskAlertGenerationStats.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (166,'Statistica Scambio Dati','Statistica Scambio Dati','controller','service',33,160,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=div_statsDataExchange;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/iRiskDataExchangeStats.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (167,'Scarica Statistica','Scarica Statistica','controller','service',33,160,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=div_statsAlertHandling;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/irisk/displayStatisticsData.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (169,'Amministrazione','Amministrazione','container','container',0,133,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (170,'Cambio Password','Cambio Password','controller','service',33,169,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=adminChangePassword;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/admin/adminChangePassword.cform;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (171,'Ricerca Utente','Ricerca Utente','controller','service',33,169,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=FIELD_DEFINITIONS_USER_ID;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/admin/adminUserSearch.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (172,'Visualizza Profilo Utente','Visualizza Profilo Utente','controller','service',33,169,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=FIELD_DEFINITIONS_EMAIL_ADDRESS;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/admin/adminUserProfile.cform;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (173,'Aggiungi Utente','Aggiungi Utente','controller','service',33,169,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=adminUserAdd;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/admin/adminUserAdd.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (174,'iMonitor','iMonitor','container','container',0,133,60,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (175,'Sommario Volo','Sommario Volo','controller','service',33,174,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=searchCriteriaForm:carrierCode;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/iMonitor/iMonitor_select_flight.html;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (176,'Messaggi ARS','Messaggi ARS','controller','service',33,174,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=searchCriteriaForm_SUBMIT;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/iMonitor/iMonitor_select_flight.html;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (177,'Statistiche','Statistiche','controller','service',33,174,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=carrierCode;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/iMonitor/iMonitor_selectmessage.html;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (178,'Messaggi API','Messaggi API','controller','service',33,174,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=carrierCode;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/iMonitor/iMonitor_selectdcs.html;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (179,'Messaggi DCS','Messaggi DCS','controller','service',33,174,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=flightNumber;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/iMonitor/iMonitor_selectpnr.html;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (180,'IAG Download Excel Template','Download Excel Template','controller','service',33,125,3600,-2,NULL,NULL,NULL,'host=mdi-iag.sita.aero;port=443;protocol=https;uri=https://mdi-iag.sita.aero/iag/secure/displayProtectedPageAction.do?source=mainmenu&destination=filedownload;search=bcs_iag_template_en_;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=;auth_passwd=;login_page=https://mdi-iag.sita.aero/iag/j_security_check;get_page=https://mdi-iag.sita.aero/iag/secure/displayProtectedPageAction.do?source=mainmenu&destination=filedownload;request_parameters=j_username=SARGOIAG+j_password=Birillo1;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (181,'IAG File Upload','File Upload','controller','service',33,125,3600,-2,NULL,NULL,NULL,'host=mdi-iag.sita.aero;port=443;protocol=https;uri=https://mdi-iag.sita.aero/iag/secure/displayProtectedPageAction.do?source=mainmenu&destination=fileupload;search=UN/US EDIFACT;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=;auth_passwd=;login_page=https://mdi-iag.sita.aero/iag/j_security_check;get_page=https://mdi-iag.sita.aero/iag/secure/displayProtectedPageAction.do?source=mainmenu&destination=fileupload;request_parameters=j_username=SARGOIAG+j_password=Birillo1;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (182,'IAG Enter Fligth Summary','Enter Fligth Summary','controller','service',33,125,3600,-2,NULL,NULL,NULL,'host=mdi-iag.sita.aero;port=443;protocol=https;uri=https://mdi-iag.sita.aero/iag/secure/displayProtectedPageAction.do?source=mainmenu&destination=flightsummary;search=flightSummary.passengerCrewMsgType;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=;auth_passwd=;login_page=https://mdi-iag.sita.aero/iag/j_security_check;get_page=https://mdi-iag.sita.aero/iag/secure/displayProtectedPageAction.do?source=mainmenu&destination=flightsummary;request_parameters=j_username=SARGOIAG+j_password=Birillo1;connection_timeout=;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (183,'RisultatiRicerca','','container','container',0,146,3600,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (184,'Risultati Ricerca Volo','Risultati Ricerca Volo','controller','service',34,183,3600,-2,NULL,NULL,NULL,'host=193.130.146.100;port=80;protocol=http;uri=http://193.130.146.100/home;search=KIA-CAG;proxy_host=;proxy_port=;proxy_protocolt=;auth_username=Cern7Ygens;auth_passwd=B2K09377X8;login_page=http://193.130.146.100/sso/signon/login.do;get_page=http://193.130.146.100/idetectdb/flightSearch.form;request_parameters=josso_username=SUP+josso_password=SUP+josso_cmd=login;search_parameters=requery=false+pageNumber=1+orderByColumn=DEP_DATE+ascDesc=DESC;search_page=http://193.130.146.100/idetectdb/flightSearch.form;connection_timeout=50000;data_receiving_timeout=;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (189,'tesr','','container','container',0,136,60,-1,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (191,'TEST SITA','','container','container',0,1,3600,-2,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (192,'TEST WS MDI','TEST WS MDI','controller','service',40,191,60,-2,NULL,NULL,NULL,'endpoint=http://appla.cedinterforze.interno.it:88/iaeInterrogazione/services/IaeServizioS023;user=pippo;password=pluto;digest=si;','','http://192.168.100.82:8080/soap/servlet/rpcrouter',0,'no_active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (194,'PORTALE STM','PORTALE STM','container','container',0,22,60,0,NULL,NULL,NULL,'',NULL,NULL,0,'active',0);
INSERT INTO objects (id, nome, descr, tipo, categoria, csc, idp, polling, working, calctype, menu, icon, paramstring, proxyDispatch, dispatch, report, status, pd) VALUES (195,'Portale Stm HomePage','PORTALE STM','controller','application',8,194,1200,0,NULL,NULL,NULL,'uri=http://portale.stmitalia.com/index.action;search=Portale amministrativo;auth_username=;auth_passwd=;proxy_host=;proxy_port=;proxy_user=;proxy_passwd=;request_method=;request_parameters=;connection_timeout=120;data_receiving_timeout=;','','http://127.0.0.1:8180/soap/servlet/rpcrouter',0,'active',0);

--INTO OBJECTS_ACTIONS
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (24,1,4,5,1);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (24,2,4,5,2);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (24,3,4,5,3);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (24,4,4,5,4);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (24,5,4,5,5);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (24,6,4,5,6);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (24,7,4,5,7);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (39,1,4,5,43);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (39,2,4,5,44);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (39,3,4,5,45);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (39,4,4,5,46);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (39,5,4,5,47);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (39,6,4,5,48);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (39,7,4,5,49);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (42,1,4,5,50);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (42,2,4,5,51);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (42,3,4,5,52);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (42,4,4,5,53);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (42,5,4,5,54);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (42,6,4,5,55);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (42,7,4,5,56);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (43,1,4,5,57);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (43,2,4,5,58);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (43,3,4,5,59);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (43,4,4,5,60);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (43,5,4,5,61);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (43,6,4,5,62);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (43,7,4,5,63);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (37,1,4,5,64);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (37,2,4,5,65);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (37,3,4,5,66);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (37,4,4,5,67);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (37,5,4,5,68);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (37,6,4,5,69);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (37,7,4,5,70);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (38,1,4,5,85);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (38,2,4,5,86);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (38,3,4,5,87);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (38,4,4,5,88);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (38,5,4,5,89);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (38,6,4,5,90);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (38,7,4,5,91);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (111,1,0,23,219);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (111,2,0,23,220);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (111,3,0,23,221);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (111,4,0,23,222);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (111,5,0,23,223);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (111,6,0,23,224);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (111,7,0,23,225);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (109,1,0,23,233);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (109,2,0,23,234);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (109,3,0,23,235);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (109,4,0,23,236);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (109,5,0,23,237);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (109,6,0,23,238);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (109,7,0,23,239);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (113,1,0,23,240);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (113,2,0,23,241);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (113,3,0,23,242);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (113,4,0,23,243);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (113,5,0,23,244);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (113,6,0,23,245);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (113,7,0,23,246);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (112,1,0,23,254);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (112,2,0,23,255);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (112,3,0,23,256);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (112,4,0,23,257);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (112,5,0,23,258);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (112,6,0,23,259);
INSERT INTO objects_actions (idProcess, dayOfWeek, startHour, endHour, idActivity) VALUES (112,7,0,23,260);